services:
  vox-student:
    image: hcktplanet/vox-student:latest
    container_name: vox-student
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - vox-student-db:/app/data
      - vox-student-whatsapp:/app/whatsapp-session

volumes:
  vox-student-db:
  vox-student-whatsapp:
