version: '3.8'

services:
  vox-student:
    image: lucianobargmann/vox-student:latest
    container_name: vox-student-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./data:/app/prisma
      - ./whatsapp-session:/app/whatsapp-session
    networks:
      - vox-student-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.vox-student.rule=Host(`vox-student.hcktplanet.com`)"
      - "traefik.http.routers.vox-student.entrypoints=websecure"
      - "traefik.http.routers.vox-student.tls.certresolver=letsencrypt"
      - "traefik.http.services.vox-student.loadbalancer.server.port=3000"

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: vox-student-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - vox-student
    networks:
      - vox-student-network

networks:
  vox-student-network:
    driver: bridge

volumes:
  vox-student-data:
