version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    command:
      # Enable Docker provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      
      # Entry points
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      
      # Redirect HTTP to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      
      # Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=luciano@hcktplanet.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      
      # Dashboard
      - --api.dashboard=true
      - --api.insecure=true  # Remove in production
      
      # Logs
      - --log.level=INFO
      - --accesslog=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik-network
    labels:
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.hcktplanet.com`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"

  vox-student:
    image: lucianobargmann/vox-student:latest
    container_name: vox-student-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./data:/app/prisma
      - ./whatsapp-session:/app/whatsapp-session
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.vox-student.rule=Host(`vox-student.hcktplanet.com`)"
      - "traefik.http.routers.vox-student.entrypoints=websecure"
      - "traefik.http.routers.vox-student.tls.certresolver=letsencrypt"
      - "traefik.http.services.vox-student.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true
